import {
  octKey,
  octMul,
  type OctValue,
} from './moufangHolonomyValidityV0';
import {
  buildFanoOctonionicLocalChannelTableV0Report,
  type FanoLocalChannelRow,
} from './fanoOctonionicLocalChannelTableV0';
import {
  buildFanoOctonionicCarrierGraphFieldV0Report,
  type FanoCarrierGraphChildNodeRow,
  type FanoCarrierGraphPrimalNodeRow,
} from './fanoOctonionicCarrierGraphFieldV0';
import {
  buildHubLayerSourceStateCapsuleV0Report,
} from './hubLayerSourceStateCapsuleV0';
import {
  buildFanoOctonionicCarrierTableV0Report,
} from './fanoOctonionicCarrierTableV0';
import {
  buildOctonionVsA3MedialCarrierDiscriminatorV0Report,
} from './octonionVsA3MedialCarrierDiscriminatorV0';

/**
 * CBF F-I Phase-1, Run 1.5 -- the LEAVES-Q GATING PROOF.
 *
 * The sovereign requires proof that candidate mixed loop words genuinely LEAVE
 * Q before any Run-2 validity diagnostic is authorized. A loop class genuinely
 * leaves Q iff the SUBALGEBRA GENERATED by the units in its derived links is
 * NOT contained in Q = {+-1, +-e3, +-e5, +-e6} -- the generated subalgebra,
 * never the final holonomy value. This module computes and reports the
 * generated subalgebra per candidate class; it assigns NO enter/exclude
 * verdict and NO octonionic-sector membership: the auditor classifies against
 * a hash-committed sealed rule this module does not see. No field-activity
 * claim, no broadcast design. Links are DERIVED from named C1/F1/capsule rows
 * (sharpening 10.2), never chosen; underdetermination ESCALATES and HOLDS the
 * affected classes.
 */

export const LEAVES_Q_METHOD = 'mixed-loop-leaves-q-gate-v0' as const;

export const LEAVES_Q_GATE_DECLARATION = {
  declaredPath: 'C:\\Dev\\202cl\\PlatonicEngine202',
  declaredBranch: 'Claude-child',
  declaredHeadAtAuthoring: '9b7bc9d',
  sealNote:
    'leaves-Q gating-proof sealed predictions (sovereign over-rule) hash-committed at 9b7bc9d; expected values and the enter/exclude rule withheld from the implementer',
} as const;

/** Verbatim from the F-I entry order GOVERNING CONSTRAINT block. */
export const GOVERNING_QUATERNIONIC_CAVEAT: string =
  'The Gate-0 pass is QUATERNIONIC. The hub link variables lie in an associative quaternion\n' +
  'subalgebra Q; the holonomy is well-defined BY ASSOCIATIVITY, not by taming non-associativity.\n' +
  'Octonion non-associativity is DORMANT for the valid observable; where it appears it appears\n' +
  'only as ill-definedness (Policy C) and as non-invariance under the illegitimate conjugation\n' +
  'gauge -- never as a richer well-defined observable. Gate 0 PASS means a QUATERNIONIC observable\n' +
  'exists; it does NOT mean the field problem is solved, and it gives the field NO octonion-non-\n' +
  'associativity support from the hub holonomy.';

export const SECTION_6_YELLOW_FLAG: string =
  'YELLOW FLAG (Gate-0 memo §6): the strong octonion-field thesis has no support from the hub\n' +
  'holonomy. Every F-I document must say so wherever it reaches for octonionic content.';

export const LEAVES_Q_SEED = 20260614 as const;
export const CYCLE_EDGE_LENGTH_BOUND = 4 as const;

export type LeavesQEdgeFamily =
  | 'hub'
  | 'birth'
  | 'response-parent-return'
  | 'response-projection-loop'
  | 'complement';

export interface LeavesQDerivedEdge {
  edgeId: string;
  family: LeavesQEdgeFamily;
  from: string;
  to: string;
  viaActionSource: string | null;
  linkUnitKeys: string[];
  sourceRows: string[];
  underdetermined: boolean;
}

export interface LeavesQCycle {
  cycleId: string;
  edgeIds: string[];
  nodeSequence: string[];
  classSignature: string;
}

export interface LeavesQClosureOutcome {
  outcomeKey: string;
  cycleCount: number;
  witnessCycleId: string;
  seedUnitKeys: string[];
  closedSetKeys: string[];
  closedSetSize: number;
  dimension: number;
  subsetOfQ: boolean;
  closureKind:
    | 'equals-Q'
    | 'quaternion-4dim-not-Q'
    | 'full-octonions-8dim'
    | 'dim-2-or-smaller'
    | 'other';
  generatorUnitCount: number;
  twoGeneratedPairExists: boolean | null;
}

export interface LeavesQClassRow {
  classSignature: string;
  cycleCount: number;
  held: boolean;
  responseFamilies: string[];
  outcomes: LeavesQClosureOutcome[];
  uniformAcrossCycles: boolean;
}

export interface LeavesQEscalationRecord {
  escalationId: string;
  context: string;
  detail: string;
  heldClassSignatures: string[];
  escalationNote: 'genuine gap or defect in the consumed carrier rows; escalates to mothership, never invented or silently fixed';
}

export interface LeavesQMockClassRow {
  classSignature: string;
  beforeOutcomeSummary: string;
  afterOutcomeSummary: string;
  changed: boolean;
}

export interface LeavesQMockReport {
  scrambleDescription: string;
  slotCount: number;
  classRows: LeavesQMockClassRow[];
  changedClassCount: number;
  determinationChanged: boolean;
}

export interface LeavesQLedgerRow {
  ledgerId: string;
  context: string;
  measurement: string;
  derivationStatus: '';
}

export interface LeavesQIntegrityIssue {
  code: string;
  message: string;
}

export interface MixedLoopLeavesQGateV0Report {
  reportId: string;
  method: typeof LEAVES_Q_METHOD;
  declaredGate: typeof LEAVES_Q_GATE_DECLARATION;
  governingQuaternionicCaveat: typeof GOVERNING_QUATERNIONIC_CAVEAT;
  yellowFlag: typeof SECTION_6_YELLOW_FLAG;
  diagnosticScope: 'computes-and-reports-only-pure-math-finite-diagnostic';
  verdictStatus: 'no-enter-exclude-verdict-auditor-classifies-against-hash-committed-sealed-rule';
  run2AuthorizationStatus: 'run-2-unauthorized-until-this-gating-proof-is-audited';
  consumedSubstrates: string[];
  seed: number;
  streamConsumptionOrder: string[];
  qSignedSetKeys: string[];
  derivationManifest: LeavesQDerivedEdge[];
  edgeCounts: {
    hub: number;
    birth: number;
    responseParentReturn: number;
    responseProjectionLoop: number;
    complement: number;
    total: number;
  };
  cycleBound: {
    edgeLengthBound: number;
    rationale: string;
  };
  inventory: {
    totalSimpleCyclesWithinBound: number;
    pureHubExcludedCount: number;
    candidateCycleCount: number;
    classCount: number;
  };
  classRows: LeavesQClassRow[];
  escalations: LeavesQEscalationRecord[];
  mock: LeavesQMockReport;
  anomalyLedger: LeavesQLedgerRow[];
  integrityIssueCount: number;
  integrityIssues: LeavesQIntegrityIssue[];
  ok: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const PRIMAL_SITES = ['A', 'B', 'C', 'D'] as const;
const NODE_ORDER = [
  'A',
  'B',
  'C',
  'D',
  'M_AB',
  'M_AC',
  'M_AD',
  'M_BC',
  'M_BD',
  'M_CD',
];

function parseSignedUnit(label: string): OctValue {
  const sign = label.startsWith('-') ? -1 : 1;
  const unitLabel = label.replace(/^[+-]/, '');
  const unit = unitLabel === '1' ? 0 : Number(unitLabel.slice(1));

  return { sign: sign as 1 | -1, unit };
}

function mulKeys(leftKey: string, rightKey: string): string {
  return octKey(octMul(parseSignedUnit(leftKey), parseSignedUnit(rightKey)));
}

/** Multiplicative closure of a set of signed basis elements (fixpoint). */
function closeUnderProduct(seedKeys: string[]): string[] {
  const closed = new Set<string>(seedKeys);
  let changed = true;

  while (changed) {
    changed = false;
    const current = [...closed];

    for (const leftKey of current) {
      for (const rightKey of current) {
        const productKey = mulKeys(leftKey, rightKey);

        if (!closed.has(productKey)) {
          closed.add(productKey);
          changed = true;
        }
      }
    }
  }

  return [...closed].sort();
}

function unitOfKey(key: string): number {
  return parseSignedUnit(key).unit;
}

function dimensionOf(closedKeys: string[]): number {
  return new Set(closedKeys.map(unitOfKey)).size;
}

const Q_SIGNED_KEYS = ['+1', '-1', '+e3', '-e3', '+e5', '-e5', '+e6', '-e6'].sort();

function isSubsetOfQ(closedKeys: string[]): boolean {
  const qSet = new Set(Q_SIGNED_KEYS);

  return closedKeys.every((key) => qSet.has(key));
}

function classifyClosure(closedKeys: string[]): LeavesQClosureOutcome['closureKind'] {
  const dimension = dimensionOf(closedKeys);
  const equalsQ =
    closedKeys.length === Q_SIGNED_KEYS.length &&
    closedKeys.every((key, index) => key === Q_SIGNED_KEYS[index]);

  if (equalsQ) {
    return 'equals-Q';
  }

  if (dimension === 8) {
    return 'full-octonions-8dim';
  }

  if (dimension === 4) {
    return 'quaternion-4dim-not-Q';
  }

  if (dimension <= 2) {
    return 'dim-2-or-smaller';
  }

  return 'other';
}

function mulberry32(seed: number): () => number {
  let state = seed >>> 0;

  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let mixed = state;
    mixed = Math.imul(mixed ^ (mixed >>> 15), mixed | 1);
    mixed ^= mixed + Math.imul(mixed ^ (mixed >>> 7), mixed | 61);

    return ((mixed ^ (mixed >>> 14)) >>> 0) / 4294967296;
  };
}

function drawPermutation(size: number, next: () => number): number[] {
  const permutation = Array.from({ length: size }, (_unused, index) => index);

  for (let index = size - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(next() * (index + 1));
    const held = permutation[index];
    permutation[index] = permutation[swapIndex];
    permutation[swapIndex] = held;
  }

  return permutation;
}

const FAMILY_TOKENS: Record<LeavesQEdgeFamily, string> = {
  hub: 'H',
  birth: 'B',
  'response-parent-return': 'Rpr',
  'response-projection-loop': 'Rpl',
  complement: 'C',
};

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

export function buildMixedLoopLeavesQGateV0Report(): MixedLoopLeavesQGateV0Report {
  const integrityIssues: LeavesQIntegrityIssue[] = [];
  const ledger: LeavesQLedgerRow[] = [];
  const escalations: LeavesQEscalationRecord[] = [];
  let ledgerCounter = 0;
  let escalationCounter = 0;

  const pushIssue = (code: string, message: string): void => {
    integrityIssues.push({ code, message });
  };
  const pushLedger = (context: string, measurement: string): void => {
    ledgerCounter += 1;
    ledger.push({
      ledgerId: `leaves-q-ledger-${String(ledgerCounter).padStart(2, '0')}`,
      context,
      measurement,
      derivationStatus: '',
    });
  };
  const pushEscalation = (context: string, detail: string): void => {
    escalationCounter += 1;
    escalations.push({
      escalationId: `leaves-q-escalation-${String(escalationCounter).padStart(2, '0')}`,
      context,
      detail,
      heldClassSignatures: [],
      escalationNote:
        'genuine gap or defect in the consumed carrier rows; escalates to mothership, never invented or silently fixed',
    });
    pushIssue('escalation', `${context}: ${detail}`);
  };

  // -------------------------------------------------------------------------
  // Substrates (READ-ONLY)
  // -------------------------------------------------------------------------
  const c1Report = buildFanoOctonionicLocalChannelTableV0Report();
  const f1Report = buildFanoOctonionicCarrierGraphFieldV0Report();
  const capsule = buildHubLayerSourceStateCapsuleV0Report();
  const carrierTable = buildFanoOctonionicCarrierTableV0Report();
  const discriminator = buildOctonionVsA3MedialCarrierDiscriminatorV0Report();

  if (!c1Report.ok) {
    pushIssue('c1-not-ok', 'C1 local channel table report is not ok.');
  }

  if (!f1Report.ok) {
    pushIssue('f1-not-ok', 'F1 carrier graph field report is not ok.');
  }

  if (!capsule.ok) {
    pushIssue('hub-capsule-not-ok', 'Hub capsule report is not ok.');
  }

  if (!carrierTable.ok) {
    pushIssue('carrier-table-not-ok', 'Carrier table report is not ok.');
  }

  if (!discriminator.ok) {
    pushIssue('discriminator-not-ok', 'Discriminator report is not ok.');
  }

  const auditGraphId = f1Report.graphSetRows[0].graphId;
  const auditEdgeRows = f1Report.edgeRows.filter((row) => row.graphId === auditGraphId);
  const auditNodeRows = f1Report.nodeRows.filter((row) => row.graphId === auditGraphId);
  const primalNodeByLabel = new Map<string, FanoCarrierGraphPrimalNodeRow>(
    auditNodeRows
      .filter(
        (row): row is FanoCarrierGraphPrimalNodeRow =>
          row.nodeRole === 'primal-source-node',
      )
      .map((row) => [row.sourceSlotId, row]),
  );
  const childNodeByToken = new Map<string, FanoCarrierGraphChildNodeRow>(
    auditNodeRows
      .filter(
        (row): row is FanoCarrierGraphChildNodeRow =>
          row.nodeRole === 'child-source-node',
      )
      .map((row) => [row.childTokenId, row]),
  );

  // Cross-check: all 3 graphs agree on each token's birth lift.
  const birthLiftByTokenAcrossGraphs = new Map<string, Set<string>>();

  for (const edgeRow of f1Report.edgeRows) {
    if (edgeRow.edgeFamily !== 'birth-edge') {
      continue;
    }

    const lifts = birthLiftByTokenAcrossGraphs.get(edgeRow.childTokenId) ?? new Set();
    lifts.add(edgeRow.signedLift);
    birthLiftByTokenAcrossGraphs.set(edgeRow.childTokenId, lifts);
  }

  for (const [tokenId, lifts] of birthLiftByTokenAcrossGraphs) {
    if (lifts.size !== 1) {
      pushEscalation(
        'birth-lift-graph-disagreement',
        `Token ${tokenId} has differing birth lifts across F1 graph sets: ${[...lifts].join(', ')}.`,
      );
    }
  }

  // -------------------------------------------------------------------------
  // PART 0 -- link derivation (derived, never chosen)
  // -------------------------------------------------------------------------
  const edges: LeavesQDerivedEdge[] = [];

  // Hub-internal flag edges from the capsule, cross-checked vs carrier table.
  const tableLiftByOrderedPair = new Map(
    carrierTable.orderedLiftRows.map((row) => [
      `${row.orderedParents[0]}->${row.orderedParents[1]}`,
      row.signedLift,
    ]),
  );

  for (const flagState of capsule.flagStates) {
    const tableLift = tableLiftByOrderedPair.get(flagState.flagId);
    const underdetermined = !tableLift || tableLift !== flagState.recomputedSignedLiftLabel;

    if (underdetermined) {
      pushEscalation(
        'hub-link-cross-check',
        `Flag ${flagState.flagId}: capsule ${flagState.recomputedSignedLiftLabel} vs carrier table ${tableLift ?? 'missing'}.`,
      );
    }

    const [from, to] = flagState.flagId.split('->');
    edges.push({
      edgeId: `hub:${flagState.flagId}`,
      family: 'hub',
      from,
      to,
      viaActionSource: null,
      linkUnitKeys: [octKey(parseSignedUnit(flagState.recomputedSignedLiftLabel))],
      sourceRows: [
        `capsule.flagStates[${flagState.flagStateId}].recomputedSignedLiftLabel = ${flagState.recomputedSignedLiftLabel}`,
        `carrierTable.orderedLiftRows[${flagState.flagId.replace('->', '·')}].signedLift = ${tableLift ?? 'MISSING'}`,
      ],
      underdetermined,
    });
  }

  // Birth edges: one directed edge per (parent, child); link units = the F1
  // birth transportResult signedLift (child lift, Q) + the RECORDED source
  // primal-quadrangle atom (F1 primal node carrierUnit).
  const transportByEdgeId = new Map(
    f1Report.carrierTransportRows.map((row) => [row.edgeId, row]),
  );

  for (const edgeRow of auditEdgeRows) {
    if (edgeRow.edgeFamily !== 'birth-edge') {
      continue;
    }

    const transportRow = transportByEdgeId.get(edgeRow.edgeId);
    const transportLift = transportRow?.transportResult;

    if (!transportLift || transportLift !== edgeRow.signedLift) {
      pushEscalation(
        'birth-transport-cross-check',
        `${edgeRow.edgeId}: edge signedLift ${edgeRow.signedLift} vs transportResult ${transportLift ?? 'missing'}.`,
      );
    }

    for (const parentNodeId of edgeRow.sourceNodeIds) {
      const parentLabel = parentNodeId.split(':').pop() as string;
      const parentNode = primalNodeByLabel.get(parentLabel);

      if (!parentNode) {
        pushEscalation(
          'birth-parent-atom-underdetermined',
          `${edgeRow.edgeId}: no F1 primal node row for parent ${parentLabel}.`,
        );
        edges.push({
          edgeId: `birth:${parentLabel}->${edgeRow.childTokenId}`,
          family: 'birth',
          from: parentLabel,
          to: edgeRow.childTokenId,
          viaActionSource: null,
          linkUnitKeys: [],
          sourceRows: [`F1 ${edgeRow.edgeId} (parent atom row MISSING)`],
          underdetermined: true,
        });
        continue;
      }

      edges.push({
        edgeId: `birth:${parentLabel}->${edgeRow.childTokenId}`,
        family: 'birth',
        from: parentLabel,
        to: edgeRow.childTokenId,
        viaActionSource: null,
        linkUnitKeys: [
          octKey(parseSignedUnit(edgeRow.signedLift)),
          octKey(parseSignedUnit(`+${parentNode.carrierUnit}`)),
        ],
        sourceRows: [
          `F1 edgeRows[${edgeRow.edgeId}].signedLift = ${edgeRow.signedLift}`,
          `F1 carrierTransportRows[${transportRow?.transportId ?? 'MISSING'}].transportResult = ${transportLift ?? 'MISSING'}`,
          `F1 nodeRows[${parentNode.nodeId}].carrierUnit = ${parentNode.carrierUnit} (recorded source primal-quadrangle atom)`,
        ],
        underdetermined: false,
      });
    }
  }

  // Response channels from C1 rows, cross-checked against F1 response edges.
  const f1ResponseByKey = new Map(
    auditEdgeRows
      .filter(
        (row) =>
          row.edgeFamily === 'parent-return-edge' ||
          row.edgeFamily === 'projection-loop-edge',
      )
      .map((row) => [
        `${(row as { childTokenId: string }).childTokenId}|${(row as { actionSourceId: string }).actionSourceId}`,
        row,
      ]),
  );
  const c1FamilyToF1Family: Record<string, string> = {
    'child-parent-return': 'parent-return-edge',
    'child-projection-loop': 'projection-loop-edge',
  };

  for (const channelRow of c1Report.localChannelRows) {
    const f1Row = f1ResponseByKey.get(
      `${channelRow.childTokenId}|${channelRow.actionSourceId}`,
    ) as
      | {
          edgeId: string;
          edgeFamily: string;
          childLeftSignedResult: string;
          sourceLeftSignedResult: string;
          expectedRecoveredSourceId: string;
        }
      | undefined;
    let underdetermined = false;

    if (!f1Row) {
      pushEscalation(
        'response-channel-f1-row-missing',
        `C1 channel ${channelRow.childTokenId}/${channelRow.actionSourceId} has no matching F1 response edge.`,
      );
      underdetermined = true;
    } else if (
      f1Row.edgeFamily !== c1FamilyToF1Family[channelRow.channelFamily] ||
      f1Row.childLeftSignedResult !== channelRow.childLeftSignedResult ||
      f1Row.sourceLeftSignedResult !== channelRow.sourceLeftSignedResult ||
      f1Row.expectedRecoveredSourceId !== channelRow.expectedRecoveredSourceId
    ) {
      pushEscalation(
        'response-channel-c1-f1-mismatch',
        `C1 channel ${channelRow.childTokenId}/${channelRow.actionSourceId} disagrees with F1 ${f1Row.edgeId}.`,
      );
      underdetermined = true;
    }

    const family: LeavesQEdgeFamily =
      channelRow.channelFamily === 'child-parent-return'
        ? 'response-parent-return'
        : 'response-projection-loop';
    edges.push({
      edgeId: `${FAMILY_TOKENS[family]}:${channelRow.childTokenId}-(action ${channelRow.actionSourceId})->${channelRow.expectedRecoveredSourceId}`,
      family,
      from: channelRow.childTokenId,
      to: channelRow.expectedRecoveredSourceId,
      viaActionSource: channelRow.actionSourceId,
      linkUnitKeys: [
        octKey(parseSignedUnit(channelRow.childLeftSignedResult)),
        octKey(parseSignedUnit(channelRow.sourceLeftSignedResult)),
      ],
      sourceRows: [
        `C1 localChannelRows[${channelRow.childTokenId}/${channelRow.actionSourceId}/${channelRow.channelFamily}].childLeftSignedResult = ${channelRow.childLeftSignedResult}`,
        `C1 localChannelRows[...].sourceLeftSignedResult = ${channelRow.sourceLeftSignedResult}`,
        `F1 edgeRows[${f1Row?.edgeId ?? 'MISSING'}] cross-check ${underdetermined ? 'FAILED' : 'ok'}`,
      ],
      underdetermined,
    });
  }

  // Complement-coupling edges from F1.
  for (const edgeRow of auditEdgeRows) {
    if (edgeRow.edgeFamily !== 'complement-coupling-edge') {
      continue;
    }

    edges.push({
      edgeId: `compl:${edgeRow.childTokenId}->${edgeRow.complementTokenId}`,
      family: 'complement',
      from: edgeRow.childTokenId,
      to: edgeRow.complementTokenId,
      viaActionSource: null,
      linkUnitKeys: [
        octKey(parseSignedUnit(edgeRow.sourceChildSignedLift)),
        octKey(parseSignedUnit(edgeRow.complementChildSignedLift)),
      ],
      sourceRows: [
        `F1 edgeRows[${edgeRow.edgeId}].sourceChildSignedLift = ${edgeRow.sourceChildSignedLift}`,
        `F1 edgeRows[${edgeRow.edgeId}].complementChildSignedLift = ${edgeRow.complementChildSignedLift}`,
      ],
      underdetermined: false,
    });
  }

  const edgeCounts = {
    hub: edges.filter((edge) => edge.family === 'hub').length,
    birth: edges.filter((edge) => edge.family === 'birth').length,
    responseParentReturn: edges.filter(
      (edge) => edge.family === 'response-parent-return',
    ).length,
    responseProjectionLoop: edges.filter(
      (edge) => edge.family === 'response-projection-loop',
    ).length,
    complement: edges.filter((edge) => edge.family === 'complement').length,
    total: edges.length,
  };

  if (
    edgeCounts.hub !== 12 ||
    edgeCounts.birth !== 12 ||
    edgeCounts.responseParentReturn !== 12 ||
    edgeCounts.responseProjectionLoop !== 12 ||
    edgeCounts.complement !== 6
  ) {
    pushIssue(
      'edge-count-mismatch',
      `Expected 12/12/12/12/6 edges, got ${edgeCounts.hub}/${edgeCounts.birth}/${edgeCounts.responseParentReturn}/${edgeCounts.responseProjectionLoop}/${edgeCounts.complement}.`,
    );
  }

  // -------------------------------------------------------------------------
  // PART 1 -- candidate mixed loop-class inventory (simple directed cycles,
  // edge-length <= bound, canonical start at the minimum node)
  // -------------------------------------------------------------------------
  const edgesByFrom = new Map<string, LeavesQDerivedEdge[]>();

  for (const edge of edges) {
    const list = edgesByFrom.get(edge.from) ?? [];
    list.push(edge);
    edgesByFrom.set(edge.from, list);
  }

  const nodeIndex = new Map(NODE_ORDER.map((node, index) => [node, index]));
  const cycles: LeavesQCycle[] = [];
  let pureHubExcludedCount = 0;

  const dfs = (
    startNode: string,
    currentNode: string,
    pathEdges: LeavesQDerivedEdge[],
    visited: Set<string>,
  ): void => {
    for (const edge of edgesByFrom.get(currentNode) ?? []) {
      if (edge.to === startNode && pathEdges.length + 1 >= 2) {
        const cycleEdges = [...pathEdges, edge];
        const families = cycleEdges.map((cycleEdge) => cycleEdge.family);
        const isPureHub = families.every((family) => family === 'hub');

        if (isPureHub) {
          pureHubExcludedCount += 1;
        } else {
          const signature = buildClassSignature(families);
          cycles.push({
            cycleId: cycleEdges.map((cycleEdge) => cycleEdge.edgeId).join(' , '),
            edgeIds: cycleEdges.map((cycleEdge) => cycleEdge.edgeId),
            nodeSequence: [startNode, ...cycleEdges.map((cycleEdge) => cycleEdge.to)],
            classSignature: signature,
          });
        }
      }

      if (pathEdges.length + 1 < CYCLE_EDGE_LENGTH_BOUND) {
        const nextNode = edge.to;
        const nextIndex = nodeIndex.get(nextNode) ?? -1;
        const startIndex = nodeIndex.get(startNode) ?? -1;

        if (nextIndex > startIndex && !visited.has(nextNode)) {
          visited.add(nextNode);
          dfs(startNode, nextNode, [...pathEdges, edge], visited);
          visited.delete(nextNode);
        }
      }
    }
  };

  for (const startNode of NODE_ORDER) {
    dfs(startNode, startNode, [], new Set([startNode]));
  }

  const classMap = new Map<string, LeavesQCycle[]>();

  for (const cycle of cycles) {
    const list = classMap.get(cycle.classSignature) ?? [];
    list.push(cycle);
    classMap.set(cycle.classSignature, list);
  }

  // -------------------------------------------------------------------------
  // PART 2 + PART 3 -- per-class generated subalgebra + structure flags
  // -------------------------------------------------------------------------
  const edgeById = new Map(edges.map((edge) => [edge.edgeId, edge]));
  const heldEdgeIds = new Set(
    edges.filter((edge) => edge.underdetermined).map((edge) => edge.edgeId),
  );

  const computeClassRows = (
    unitKeysByEdgeId: Map<string, string[]>,
  ): LeavesQClassRow[] =>
    [...classMap.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([classSignature, classCycles]) => {
        const held = classCycles.some((cycle) =>
          cycle.edgeIds.some((edgeId) => heldEdgeIds.has(edgeId)),
        );
        const responseFamilies = [
          ...new Set(
            classCycles[0].edgeIds
              .map((edgeId) => edgeById.get(edgeId)?.family)
              .filter(
                (family) =>
                  family === 'response-parent-return' ||
                  family === 'response-projection-loop',
              ) as string[],
          ),
        ].sort();

        if (held) {
          return {
            classSignature,
            cycleCount: classCycles.length,
            held: true,
            responseFamilies,
            outcomes: [],
            uniformAcrossCycles: true,
          };
        }

        const outcomeMap = new Map<
          string,
          { cycles: LeavesQCycle[]; closedKeys: string[]; seedKeys: string[] }
        >();

        for (const cycle of classCycles) {
          const seedKeys = [
            ...new Set(
              cycle.edgeIds.flatMap(
                (edgeId) => unitKeysByEdgeId.get(edgeId) ?? [],
              ),
            ),
          ].sort();
          const closedKeys = closeUnderProduct(seedKeys);
          const outcomeKey = closedKeys.join(',');
          const entry = outcomeMap.get(outcomeKey) ?? {
            cycles: [],
            closedKeys,
            seedKeys,
          };
          entry.cycles.push(cycle);
          outcomeMap.set(outcomeKey, entry);
        }

        const outcomes: LeavesQClosureOutcome[] = [...outcomeMap.entries()]
          .sort(([, left], [, right]) => right.cycles.length - left.cycles.length)
          .map(([outcomeKey, entry]) => {
            const subsetOfQ = isSubsetOfQ(entry.closedKeys);
            const generatorUnits = new Set(entry.seedKeys.map(unitOfKey));
            let twoGeneratedPairExists: boolean | null = null;

            if (!subsetOfQ) {
              twoGeneratedPairExists = false;

              for (let i = 0; i < entry.seedKeys.length && !twoGeneratedPairExists; i += 1) {
                for (let j = i + 1; j < entry.seedKeys.length; j += 1) {
                  const pairClosure = closeUnderProduct([
                    entry.seedKeys[i],
                    entry.seedKeys[j],
                  ]);

                  if (pairClosure.join(',') === outcomeKey) {
                    twoGeneratedPairExists = true;
                    break;
                  }
                }
              }
            }

            return {
              outcomeKey,
              cycleCount: entry.cycles.length,
              witnessCycleId: entry.cycles[0].cycleId,
              seedUnitKeys: entry.seedKeys,
              closedSetKeys: entry.closedKeys,
              closedSetSize: entry.closedKeys.length,
              dimension: dimensionOf(entry.closedKeys),
              subsetOfQ,
              closureKind: classifyClosure(entry.closedKeys),
              generatorUnitCount: generatorUnits.size,
              twoGeneratedPairExists,
            };
          });

        return {
          classSignature,
          cycleCount: classCycles.length,
          held: false,
          responseFamilies,
          outcomes,
          uniformAcrossCycles: outcomes.length === 1,
        };
      });

  const trueUnitKeysByEdgeId = new Map(
    edges.map((edge) => [edge.edgeId, edge.linkUnitKeys]),
  );
  const classRows = computeClassRows(trueUnitKeysByEdgeId);

  for (const classRow of classRows) {
    if (!classRow.uniformAcrossCycles) {
      pushLedger(
        `non-uniform-class:${classRow.classSignature}`,
        `Class ${classRow.classSignature} has ${classRow.outcomes.length} distinct closure outcomes across its ${classRow.cycleCount} cycles (reported per outcome).`,
      );
    }
  }

  if (escalations.length > 0) {
    const heldSignatures = classRows
      .filter((row) => row.held)
      .map((row) => row.classSignature);

    for (const escalation of escalations) {
      escalation.heldClassSignatures = heldSignatures;
    }
  }

  // -------------------------------------------------------------------------
  // PART 4 -- anti-staple / mock
  // -------------------------------------------------------------------------
  const streamConsumptionOrder = [
    '1. mock-solution scramble: one derangement of the flattened derived link-unit slots + per-slot sign bits',
  ];
  const stream = mulberry32(LEAVES_Q_SEED);
  const slots: Array<{ edgeId: string; position: number }> = [];

  for (const edge of edges) {
    edge.linkUnitKeys.forEach((_unitKey, position) => {
      slots.push({ edgeId: edge.edgeId, position });
    });
  }

  const slotValues = slots.map(
    (slot) => (trueUnitKeysByEdgeId.get(slot.edgeId) as string[])[slot.position],
  );
  let derangement = drawPermutation(slots.length, stream);

  while (derangement.some((target, index) => target === index)) {
    derangement = drawPermutation(slots.length, stream);
  }

  const scrambledByEdgeId = new Map<string, string[]>(
    edges.map((edge) => [edge.edgeId, [...edge.linkUnitKeys]]),
  );

  slots.forEach((slot, index) => {
    const base = parseSignedUnit(slotValues[derangement[index]]);
    const flip = stream() < 0.5;
    const value: OctValue = {
      sign: (flip ? -1 * base.sign : base.sign) as 1 | -1,
      unit: base.unit,
    };
    (scrambledByEdgeId.get(slot.edgeId) as string[])[slot.position] = octKey(value);
  });

  const scrambledClassRows = computeClassRows(scrambledByEdgeId);
  const summarizeOutcomes = (row: LeavesQClassRow): string =>
    row.held
      ? 'HELD'
      : row.outcomes
          .map(
            (outcome) =>
              `${outcome.closureKind}(dim ${outcome.dimension}, subsetOfQ ${outcome.subsetOfQ}) x${outcome.cycleCount}`,
          )
          .join(' | ');
  const mockClassRows: LeavesQMockClassRow[] = classRows.map((row) => {
    const scrambledRow = scrambledClassRows.find(
      (candidate) => candidate.classSignature === row.classSignature,
    ) as LeavesQClassRow;
    const beforeSummary = summarizeOutcomes(row);
    const afterSummary = summarizeOutcomes(scrambledRow);

    return {
      classSignature: row.classSignature,
      beforeOutcomeSummary: beforeSummary,
      afterOutcomeSummary: afterSummary,
      changed: beforeSummary !== afterSummary,
    };
  });
  const changedClassCount = mockClassRows.filter((row) => row.changed).length;
  const mock: LeavesQMockReport = {
    scrambleDescription:
      'seeded derangement of the flattened derived link-unit slots across all edges + independent sign flips (anti-staple: the closure computation must read the derived links, not constants)',
    slotCount: slots.length,
    classRows: mockClassRows,
    changedClassCount,
    determinationChanged: changedClassCount > 0,
  };

  if (!mock.determinationChanged) {
    pushIssue(
      'mock-solution-determination-survived',
      'The scrambled link assignment left every per-class generated-subalgebra determination unchanged; the computation is reading constants. RUN VOID.',
    );
  }

  // -------------------------------------------------------------------------
  // Integrity (well-formedness only)
  // -------------------------------------------------------------------------
  for (const edge of edges) {
    if (edge.sourceRows.length === 0) {
      pushIssue('manifest-entry-missing-source-row', edge.edgeId);
    }
  }

  if (classRows.length !== classMap.size) {
    pushIssue('class-table-incomplete', `${classRows.length} vs ${classMap.size}`);
  }

  for (const row of ledger) {
    if (row.derivationStatus !== '') {
      pushIssue('ledger-derivation-status-not-empty', row.ledgerId);
    }
  }

  return {
    reportId: `${LEAVES_Q_METHOD}:carrier-graph-mixed-loop-classes`,
    method: LEAVES_Q_METHOD,
    declaredGate: LEAVES_Q_GATE_DECLARATION,
    governingQuaternionicCaveat: GOVERNING_QUATERNIONIC_CAVEAT,
    yellowFlag: SECTION_6_YELLOW_FLAG,
    diagnosticScope: 'computes-and-reports-only-pure-math-finite-diagnostic',
    verdictStatus:
      'no-enter-exclude-verdict-auditor-classifies-against-hash-committed-sealed-rule',
    run2AuthorizationStatus: 'run-2-unauthorized-until-this-gating-proof-is-audited',
    consumedSubstrates: [
      'fanoOctonionicLocalChannelTableV0 (C1: 24 channel rows; READ-ONLY)',
      `fanoOctonionicCarrierGraphFieldV0 (F1 transport rows; audit graph = ${auditGraphId}; READ-ONLY)`,
      'hubLayerSourceStateCapsuleV0 (12 hub flag links; READ-ONLY)',
      'fanoOctonionicCarrierTableV0 (ordered lifts cross-check; READ-ONLY)',
      'moufangHolonomyValidityV0 (Gate-0 algebra core: octMul/octKey, the consumed product law; heavy builder NOT executed)',
      'octonionVsA3MedialCarrierDiscriminatorV0 (ok-status; READ-ONLY)',
    ],
    seed: LEAVES_Q_SEED,
    streamConsumptionOrder,
    qSignedSetKeys: Q_SIGNED_KEYS,
    derivationManifest: edges,
    edgeCounts,
    cycleBound: {
      edgeLengthBound: CYCLE_EDGE_LENGTH_BOUND,
      rationale:
        'the minimal mixed classes; a longer word can only extend a class generator set, and a superset of generators generates a superset subalgebra -- the leaves-Q question is settled at the minimal classes',
    },
    inventory: {
      totalSimpleCyclesWithinBound: cycles.length + pureHubExcludedCount,
      pureHubExcludedCount,
      candidateCycleCount: cycles.length,
      classCount: classRows.length,
    },
    classRows,
    escalations,
    mock,
    anomalyLedger: ledger,
    integrityIssueCount: integrityIssues.length,
    integrityIssues,
    ok: integrityIssues.length === 0,
  };
}

function buildClassSignature(families: LeavesQEdgeFamily[]): string {
  const counts = new Map<string, number>();

  for (const family of families) {
    const token = FAMILY_TOKENS[family];
    counts.set(token, (counts.get(token) ?? 0) + 1);
  }

  return [...counts.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([token, count]) => (count === 1 ? token : `${count}${token}`))
    .join('+');
}
