"""THE CARGO BETWEEN DOORS — the mothership's §133 for C-11b: the walk knows at each crossing only {door, side}, never a lifted
edge. How does the cargo get from the entry face to the exit face, and which corner's e_c applies? (§23 D3 amended.)
DEFINITIONS, fixed before the run:
  E1 THE CARGO RIDES EVERY CORNER OF THE FACE AT ONCE — no: the cargo is ONE role at ONE corner (D1 stands); what rides the
     face at once is the WALK'S TRANSPORT: a partial map on the door face's corner set (its total space ⊔_c P(c)), so at a
     crossing the door applies e_c at WHICHEVER corner the cargo is at — all of e = (e_c) at once, never one chosen corner.
     This is why descent (§18) matters: e is lawful exactly when it commutes with the face's own edges.
  E2 THE LEG between the entry face E and the exit face X of one cell, computed from the two faces alone (the cell's own
     combinatorics — no position): a corner on BOTH faces keeps its cargo (identity); a corner c of E off X passes along
     the cell's edge c–d to a corner d of X off E when that edge is the ONLY one from c into X∖E and the only one from d
     into E∖X (the cell's own matching — it takes J_cd); any other corner's cargo does not pass (a true absence).
  E3 HOME is the walk's own: Γ(w) = 1 on the deck group (here Z × Z3, generated by g and h, commuting). AWAY = two words
     with Γ(w1) = Γ(w2) — the same base position (0030 §2 reading 2).
THE ROOM (mine): the triangular prism (flow F · t-cell T · phi P at bottom with hand triple X, their lifted copies F' T' P'
  on top with Y, vertical edges the copies) with TWO doors: g = top → bottom (translation, F'↦F, T'↦T, P'↦P) and
  h = side square FTT'F' → side square TPP'T' (a third-turn about the axis: F↦T, T↦P, T'↦P', F'↦T'); the third side is
  bounded. Each door's transport GIVEN (the instrument's stand-in: the largest lawful one built line by line, §18 — ⚠).
SEALED BEFORE THE RUN (1,764 rooms; the cargo starts at a role of F, entry face the bottom):
 L1 every word's transport is a partial injection (no two cargos land on one (corner, role))                 0 failures
 L2 CURVATURE at home — h·h·h (home: a third-turn three times) or g·h·g⁻¹·h⁻¹ (home: the commutator) brings a
    cargo home MOVED                                                                                        > 0 rooms
 L3 PRESENCE route-dependent at one position — g·h and h·g (the same position; the deck is abelian)         > 0 rooms
 L4 IDENTITY route-dependent at one position — the same two words deliver a cargo as different (corner, role) > 0 rooms
 L5 a spur never moves a cargo: g·g⁻¹·g against g, h·h⁻¹·h against h — a restriction                        0 failures
 L6 CONTROL — every corner one cast, every J and every door the identity: no cargo moved, no identity
    disagreement (presence may still differ: a leg loses a corner the cell does not match — reported)       0 and 0
"""
import os, sys, itertools, collections
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from born_face_reading import HAND_TF, HAND_TP, J_FP, inv, comp
from descent_at_the_door import line_structure, line_pair_map, lawful
from inside_midpoint_trace import load

FACES = {"bottom": ["F", "T", "P"], "top": ["F'", "T'", "P'"], "S1": ["F", "T", "T'", "F'"], "S2": ["T", "P", "P'", "T'"]}
DOORS = {"g": ("top", "bottom"), "h": ("S1", "S2")}                      # exit face → entry face, corner i ↦ corner i

def build(JX, JY, casts):
    """edges of the prism: node pair → partial map"""
    C = {"F": casts[0], "T": casts[1], "P": casts[2], "F'": casts[0], "T'": casts[1], "P'": casts[2]}
    E = {}
    def link(a, b, m): E[(a, b)] = m; E[(b, a)] = inv(m)
    for i, (a, b) in enumerate([("F", "T"), ("T", "P"), ("P", "F")]):
        link(a, b, JX[i]); link(a + "'", b + "'", JY[i]); link(a, a + "'", {r: r for r in C[a]})
    return C, E

def face_Js(E, face):
    k = len(face); return [E[(face[i], face[(i + 1) % k])] for i in range(k)]

def given(Jexit, Jentry, corners):
    """the largest lawful door transport built line by line (§18) — the person's stand-in"""
    k = len(Jexit); LY, _ = line_structure(Jexit, corners); LX, _ = line_structure(Jentry, corners)
    e = [dict() for _ in range(k)]; used = set()
    for ly in LY:
        for j, lx in enumerate(LX):
            if j in used or lx["shape"] != ly["shape"]: continue
            for c, d in line_pair_map(ly, lx, 0, k).items(): e[c].update(d)
            used.add(j); break
    assert lawful(e, Jexit, Jentry)
    return e

def door_maps(C, E, identity_doors=False):
    out = {}
    for d, (fx, fe) in DOORS.items():
        X, N = FACES[fx], FACES[fe]
        if identity_doors: e = [{r: r for r in C[X[i]] if r in C[N[i]]} for i in range(len(X))]
        else: e = given(face_Js(E, X), face_Js(E, N), [C[c] for c in X])
        out[d] = {X[i]: (N[i], e[i]) for i in range(len(X))}            # corner of the exit face → (entry corner, e_c)
        out[d.upper()] = {N[i]: (X[i], inv(e[i])) for i in range(len(X))}
    return out

ADJ = {("F", "T"), ("T", "P"), ("P", "F"), ("F'", "T'"), ("T'", "P'"), ("P'", "F'"), ("F", "F'"), ("T", "T'"), ("P", "P'")}
def adj(a, b): return (a, b) in ADJ or (b, a) in ADJ

def leg(E, entry, exit_):
    """E2 — the cell's own matching from the entry face to the exit face: corner → (corner, map)"""
    A, B = set(FACES[entry]), set(FACES[exit_])
    out = {c: (c, None) for c in A & B}
    for c in A - B:
        ds = [d for d in B - A if adj(c, d)]
        if len(ds) == 1 and len([x for x in A - B if adj(x, ds[0])]) == 1: out[c] = (ds[0], E[(c, ds[0])])
    return out

def carry(E, D, word, start_corner, roles, start_face="bottom"):
    """the cargo's transport along a door word: start role → (corner, role)"""
    st = {r: (start_corner, r) for r in roles}; face = start_face
    for L in word:
        fx, fe = DOORS[L.lower()] if L.islower() else DOORS[L.lower()][::-1]
        lg = leg(E, face, fx); new = {}
        for r0, (c, r) in st.items():
            if c not in lg: continue
            d, m = lg[c]
            r2 = r if m is None else m.get(r)
            if r2 is None: continue
            c2, e = D[L][d]
            r3 = e.get(r2)
            if r3 is not None: new[r0] = (c2, r3)
        st, face = new, fe
    return st

def run():
    bad, hit = collections.Counter(), collections.Counter()
    casts = [load("flow")["roles"], load("t-cell")["roles"], load("phi")["roles"]]
    triples = list(itertools.product(HAND_TF, HAND_TP, J_FP)); ex = {}
    for t1, t2 in itertools.product(triples, triples):
        JX = [inv(HAND_TF[t1[0]]), HAND_TP[t1[1]], inv(J_FP[t1[2]])]; JY = [inv(HAND_TF[t2[0]]), HAND_TP[t2[1]], inv(J_FP[t2[2]])]
        C, E = build(JX, JY, casts); D = door_maps(C, E)
        F = casts[0]
        run_ = lambda w: carry(E, D, w, "F", F)
        for w in ("g", "h", "gh", "hg", "ghGH", "hhh"):
            fw = run_(w)
            if len(set(fw.values())) != len(fw): bad["L1"] += 1
        moved = False
        for w in ("hhh", "ghGH"):
            fw = run_(w); m = [(r, v) for r, v in fw.items() if v != ("F", r)]
            if m: moved = True; ex.setdefault("L2", (w, t1, t2, m[:2]))
        hit["L2"] += moved
        a, b = run_("gh"), run_("hg")
        pres = set(a) != set(b); ident = any(a[r] != b[r] for r in set(a) & set(b))
        hit["L3"] += pres; hit["L4"] += ident
        if ident: ex.setdefault("L4", (t1, t2, [(r, a[r], b[r]) for r in set(a) & set(b) if a[r] != b[r]][:1]))
        for w, s in (("g", "gGg"), ("h", "hHh")):
            fw, fs = run_(w), run_(s)
            if any(fw.get(r) != v for r, v in fs.items()): bad["L5"] += 1
    # L6 control: one cast everywhere, identity maps
    R = casts[0]; one = {r: r for r in R}
    C, E = build([one] * 3, [one] * 3, [R] * 3); D = door_maps(C, E, identity_doors=True)
    ctl = {w: carry(E, D, w, "F", R) for w in ("hhh", "ghGH", "gh", "hg")}
    c_moved = sum(1 for w in ("hhh", "ghGH") for r, v in ctl[w].items() if v != ("F", r))
    c_ident = sum(1 for r in set(ctl["gh"]) & set(ctl["hg"]) if ctl["gh"][r] != ctl["hg"][r])
    c_pres = len(set(ctl["gh"]) ^ set(ctl["hg"]))
    n = len(triples) ** 2
    print(f"THE CARGO BETWEEN DOORS — {n} rooms (the prism, two doors g and h), the cargo from F on the bottom face")
    print(f" L1  maps injective: failures {bad['L1']}   (sealed 0)")
    print(f" L2  home (h·h·h or g·h·g⁻¹·h⁻¹) with a cargo MOVED: {hit['L2']} of {n}   (sealed > 0) · e.g. {ex.get('L2')}")
    print(f" L3  PRESENCE differs, g·h against h·g (one position): {hit['L3']} of {n}   (sealed > 0)")
    print(f" L4  IDENTITY differs, g·h against h·g: {hit['L4']} of {n}   (sealed > 0) · e.g. {ex.get('L4')}")
    print(f" L5  a spur moved a cargo: {bad['L5']}   (sealed 0)")
    print(f" L6  CONTROL (one cast, identity maps): moved {c_moved} · identity disagreements {c_ident}   (sealed 0, 0) · "
          f"presence differs on {c_pres} roles (the legs' own absences, not curvature) · cargos home after h·h·h {len(ctl['hhh'])} of {len(R)}")

if __name__ == "__main__":
    run()
