"""THE LIFT, SETTLED IN TYPE THEORY (Arman, 2026-09-23: "your lift question must be settled in the background of
intuitionistic type theory, HoTT, and those areas where we lift from them the concept-space idea").
Dictionary under test: a concept-space is a TYPE (an h-set with relational structure; roles = its points — P0: "instances are
the concept-space points"); the layer is a FAMILY over the base's 1-skeleton; the midpoint is a homotopy PUSHOUT; the face's
world is a SET-TRUNCATION; a door is DESCENT DATA. Each line below is a claim that could be false; SEALED BEFORE THE RUN.
Homotopy colimits of diagrams of SETS are modelled exactly by their graphs (a set is a discrete space; a hocolim of a
diagram of sets over a graph-shaped index is a 1-dimensional complex): a component is contractible iff it is a tree, and
its first Betti number counts its independent circles.

 T1 THE MIDPOINT NEEDS NO TRUNCATION: the homotopy pushout of sets along two EMBEDDINGS is a set (its double
    mapping cylinder is a forest: #components = |A| + |B| − |K|)                                    0 failures
    CONTROL — a span whose legs are NOT injective makes circles                                     > 0
 T2 THE FACE IS WHERE TRUNCATION HAPPENS: the hocolim of the cyclic diagram A–B–C–A has exactly one independent
    circle per PERIODIC ORBIT of the residue h_A (fixed points included)                             0 failures
    … and its set-truncation (π₀) restricted to A is 0031 §3.2's face world (the orbits of h_A)      0 failures
 T3 REFINE-AT-SET-LEVEL POOLS EXACTLY WHERE THE RESIDUE MOVES: π₀ of the total space over a face holds two roles of
    one corner in one class ⇔ that corner's residue has Mov ≠ ∅                                     0 disagreements
 T4 THE DOOR IS DESCENT DATA: over two triangle boundaries carrying families, a door transport natural over the
    boundaries — free at one corner, forced at the others — exists iff it INTERTWINES the residues; with a TOTAL
    corner map, iff the residues have the SAME CYCLE–PATH TYPE (partial injections, n = 4, all 24 bijections tried)
        existence by brute force ⇔ same cycle–path type                                            0 disagreements
        an intertwining corner map, forced round the boundary, closes the loop                       0 failures
        a non-intertwining one, forced round, does NOT close                                         0 exceptions
        an orientation-REVERSING door: the same with h₂⁻¹                                           0 disagreements
 T5 ON THE FIXTURES: the first face's 42 residues at base Flow fall into cycle–path classes; a door between two of
    these faces can carry a total corner map only within a class                                    (reported)
"""
import random, itertools, collections

def inv(f): return {v: k for k, v in f.items()}
def comp(g, f): return {x: g[y] for x, y in f.items() if y in g}                # g∘f, f first

def components(nodes, edges):
    par = {n: n for n in nodes}
    def find(x):
        while par[x] != x: par[x] = par[par[x]]; x = par[x]
        return x
    for a, b in edges:
        ra, rb = find(a), find(b)
        if ra != rb: par[ra] = rb
    g = collections.defaultdict(set)
    for n in nodes: g[find(n)].add(n)
    return list(g.values())

def rnd_pinj(src, dst, rng, total=False):
    src, dst = list(src), list(dst)
    k = min(len(src), len(dst)) if total else rng.randint(0, min(len(src), len(dst)))
    xs = rng.sample(src, k); return dict(zip(xs, rng.sample(dst, k)))

def orbits_partition(h, X):
    """the equivalence on X generated by x ~ h(x)"""
    return {frozenset(c) for c in components(X, list(h.items()))}

def periodic_orbits(h):
    seen, n = set(), 0
    for x in h:
        if x in seen: continue
        path, y = [x], h[x]
        while y in h and y != x and y not in path: path.append(y); y = h[y]
        if y == x: n += 1; seen.update(path)
    return n

def cycle_path_type(h, X):
    """the conjugacy invariant of a partial injection of X: the multiset of its cycle lengths and path lengths"""
    X = list(X); image = set(h.values()); cyc, pth, seen = [], [], set()
    for x in X:                                                   # paths start at points with no preimage
        if x in image: continue
        n, y = 0, x
        while y in h: y = h[y]; n += 1
        pth.append(n)
        y = x; seen.add(y)
        while y in h: y = h[y]; seen.add(y)
    for x in X:
        if x in seen: continue
        n, y = 1, h[x]; seen.add(x)
        while y != x: seen.add(y); y = h[y]; n += 1
        cyc.append(n)
    return (tuple(sorted(cyc)), tuple(sorted(pth)))

def run(seed_=291, trials=4000):
    rng = random.Random(seed_); bad, hit = collections.Counter(), collections.Counter()
    # ── T1 ─────────────────────────────────────────────────────────────────────────────────────────────────
    for _ in range(trials):
        A, B = [("A", i) for i in range(6)], [("B", i) for i in range(6)]
        J = rnd_pinj(A, B, rng)                                                       # K = dom J, both legs embeddings
        K = [("K", i) for i in range(len(J))]
        E = [e for k, (a, b) in zip(K, J.items()) for e in ((k, a), (k, b))]
        if len(components(A + B + K, E)) != len(A) + len(B) - len(K): bad["T1"] += 1
        f = {k: rng.choice(A) for k in K}; g = {k: rng.choice(B) for k in K}               # CONTROL: arbitrary legs
        E2 = [e for k in K for e in ((k, f[k]), (k, g[k]))]
        if len(components(A + B + K, E2)) != len(A) + len(B) - len(K): hit["T1ctl"] += 1
    # ── T2, T3 ─────────────────────────────────────────────────────────────────────────────────────────────
    for _ in range(trials):
        A, B, C = [("A", i) for i in range(6)], [("B", i) for i in range(6)], [("C", i) for i in range(6)]
        J_AB, J_BC, J_CA = rnd_pinj(A, B, rng), rnd_pinj(B, C, rng), rnd_pinj(C, A, rng)
        nodes, E = A + B + C, list(J_AB.items()) + list(J_BC.items()) + list(J_CA.items())
        comps = components(nodes, E)
        betti = len(E) - len(nodes) + len(comps)
        h = comp(J_CA, comp(J_BC, J_AB))
        if betti != periodic_orbits(h): bad["T2"] += 1
        if betti: hit["T2circles"] += betti
        if {frozenset(c & set(A)) for c in comps if c & set(A)} != orbits_partition(h, A): bad["T2pi0"] += 1
        pooled = any(len([x for x in c if x[0] == "A"]) > 1 for c in comps)
        if pooled != any(x != y for x, y in h.items()): bad["T3"] += 1
    # ── T4 ─────────────────────────────────────────────────────────────────────────────────────────────────
    n = 4; X = list(range(n)); perms = list(itertools.permutations(X))
    for _ in range(1500):
        J1 = [rnd_pinj(X, X, rng) for _ in range(3)]; J2 = [rnd_pinj(X, X, rng) for _ in range(3)]
        h1 = comp(J1[2], comp(J1[1], J1[0])); h2 = comp(J2[2], comp(J2[1], J2[0]))      # both based at corner 1
        for reverse in (False, True):
            target = inv(h2) if reverse else h2
            exists = any({p[x]: p[y] for x, y in h1.items()} == target for p in perms)   # e ∘ h1 ∘ e⁻¹ = h2^±
            same = cycle_path_type(h1, X) == cycle_path_type(target, X)
            if exists != same: bad["T4rev" if reverse else "T4"] += 1
            if not reverse:
                for p in perms:
                    e1 = dict(enumerate(p))
                    inter = {e1[x]: e1[y] for x, y in h1.items()} == h2
                    # force round the boundary: e2 = J2[0] e1 J1[0]⁻¹ on im J1[0], … and back to corner 1
                    e2 = comp(J2[0], comp(e1, inv(J1[0]))); e3 = comp(J2[1], comp(e2, inv(J1[1])))
                    back = comp(J2[2], comp(e3, inv(J1[2])))                               # e1 as the loop returns it
                    closes = all(back.get(y) == e1[y] for y in back) and set(back) == set(h1.values())
                    hit["T4inter" if inter else "T4non"] += 1
                    if inter and not closes: bad["T4close"] += 1
                    if not inter and closes and set(h1) == set(X): bad["T4open"] += 1
    print(f"T1  pushout of sets along embeddings is a set: failures {bad['T1']}   (sealed 0)   CONTROL circles in {hit['T1ctl']} of {trials}   (sealed > 0)")
    print(f"T2  one circle per periodic orbit of h: failures {bad['T2']}   (sealed 0) · circles forgotten by π₀ across the trials: {hit['T2circles']}")
    print(f"    π₀ restricted to A = the orbits of h (0031's face world): failures {bad['T2pi0']}   (sealed 0)")
    print(f"T3  π₀ pools two roles of one corner ⇔ Mov ≠ ∅: disagreements {bad['T3']}   (sealed 0)")
    print(f"T4  door exists ⇔ same cycle–path type: disagreements {bad['T4']} · reversing door {bad['T4rev']}   (sealed 0, 0)")
    print(f"    intertwining corner map closes round the boundary: failures {bad['T4close']} of {hit['T4inter']} · non-intertwining (total h) closes anyway: {bad['T4open']} (of {hit['T4non']} non-intertwining tried)   (sealed 0, 0)")
    # ── T5 ─────────────────────────────────────────────────────────────────────────────────────────────────
    from born_face_reading import HAND_TF, HAND_TP, J_FP
    from inside_midpoint_trace import load
    flow = load("flow")["roles"]; classes = collections.defaultdict(list)
    for fp, tf, tp in itertools.product(J_FP, HAND_TF, HAND_TP):
        h = comp(inv(J_FP[fp]), comp(HAND_TP[tp], inv(HAND_TF[tf])))
        classes[cycle_path_type(h, flow)].append(f"{fp}+{tf}+{tp}")
    print(f"T5  the first face at base Flow: {len(classes)} cycle–path classes over 42 triples — class sizes {sorted((len(v) for v in classes.values()), reverse=True)}")
    big = max(classes.items(), key=lambda kv: len(kv[1]))
    print(f"    the largest class, type {big[0]}: {len(big[1])} triples — a door between two of THESE faces can carry a total corner map; across classes it cannot")

if __name__ == "__main__":
    run()
